Repository SuperBananeMan/gitgroupe7, pull requests merged in 2023-12, with the labels that each got.

#7 Feedback system
  feedback_system/feedback_html.html
Labels: feature

#10 Doc
  doc/someDoc.md
Labels: documentation

#11 finished ai simulation
  fighting_simulation/simulation.html
Labels: feature

#12 T bagging
  IA.java
Labels: enhancement, feature
